#!/bin/bash

echo $0 $1 $2

OPTIONS=$(cat ../data/ops.conf)
select opt in $OPTIONS; do
    if [ "$opt" = "Quit" ]; then
     echo done
     exit
    elif [ "$opt" = "Hello" ]; then
     echo Hello World
    else
     clear
     echo bad option
    fi
done
